### ISSUE TITLE
Dropdown for Minecraft Versions based on eggs pterodactyl

### ISSUE THREAD

**Issue by leadvic** [STIV-Minecraft/STIV_Minecraft_Calculator#4]
- In each component the user must be able to add the Minecraft Version of the server he/she wants
- Ideally it should be shown similar as the link provided https://github.com/parkervcp/eggs/tree/master/game_eggs/minecraft so that it is categorized between bedrock, java, proxy.
- The options must include not only the options shown on the link provided but also the following (Java):

  - [Bungeecord](https://pterodactyl.stiv.tech/admin/nests/egg/4)
  - [Vanilla Minecraft](https://pterodactyl.stiv.tech/admin/nests/egg/5)

**Comment by Jiroma** [comment]
other item in the component with price 0
